## .github/workflows/deploy.yml
## Copyright 2025 Alexandru Mihai Buzduc
#
# This work may be distributed and/or modified under the
# conditions of the LaTeX Project Public License, either version 1.3c
# of this license or (at your option) any later version.
# The latest version of this license is in
#   http://www.latex-project.org/lppl.txt
# and version 1.3 or later is part of all distributions of LaTeX
# version 2005/12/01 or later.
#
# This work has the LPPL maintenance status `maintained'.
#
# The Current Maintainer of this work is Alexandru Mihai Buzduc.
#
# This work consists of the files listed in src/lppl-files.txt.

name: Deploy to Neocities

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3.0.2
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: src
          cleanup: true
          neocities_supporter: false
          preview_before_deploy: true
